INSERT INTO javascript_users (username, password) VALUES ('reza', 'secret1')
INSERT INTO javascript_users (username, password) VALUES ('nicole', 'secret1')
INSERT INTO javascript_users (username, password) VALUES ('zehra', 'secret1')
INSERT INTO javascript_users (username, password) VALUES ('inaya', 'secret1')
INSERT INTO javascript_groups (username, group_name) VALUES ('reza', 'javascript_user')
INSERT INTO javascript_groups (username, group_name) VALUES ('nicole', 'javascript_user')
INSERT INTO javascript_groups (username, group_name) VALUES ('zehra', 'javascript_user')
INSERT INTO javascript_groups (username, group_name) VALUES ('inaya', 'javascript_user')
