INSERT INTO javascript_users (username, password) VALUES ('reza', 'PBKDF2WithHmacSHA256:2048:/f8eHmKcXwYet8I8fIvj/Q==:YHY8eDuFwjzT8ax80qZVKomBS8X9fc1k+pZzvm/HL48=')
INSERT INTO javascript_users (username, password) VALUES ('nicole', 'PBKDF2WithHmacSHA256:2048:MQ9oBP/0j/hGzxb5dX1Upw==:BOW7/T9HoiUuXwT2ugUnG9crTVcCjLIyAIb5mTwaA7g=')
INSERT INTO javascript_users (username, password) VALUES ('zehra', 'PBKDF2WithHmacSHA256:2048:hiw+dJ4nXkFZSEsSIOfYfw==:vifrMLR9d2KGb1T2Ct/3/Pm3TKt6mRB0evkPJ/P8j8s=')
INSERT INTO javascript_users (username, password) VALUES ('inaya', 'PBKDF2WithHmacSHA256:2048:WuS+mlt1Iakr9yeFQv19Dw==:mtu+DyK2aIdv3i8wZlOlAER/3MMS030Jf0x408oMzz8=')
INSERT INTO javascript_groups (username, group_name) VALUES ('reza', 'javascript_user')
INSERT INTO javascript_groups (username, group_name) VALUES ('nicole', 'javascript_user')
INSERT INTO javascript_groups (username, group_name) VALUES ('zehra', 'javascript_user')
INSERT INTO javascript_groups (username, group_name) VALUES ('inaya', 'javascript_user')
